apiVersion: v1
kind: Service
metadata:
  name: hack-day-lb
  labels:
    name: hack-day
spec:
  type: LoadBalancer # NodePort or ClusterIp
  externalTrafficPolicy: Local
  selector:
    name: hack-day
  ports:
    - name: mongodb-lb
      protocol: TCP
      port: 27017
      targetPort: mongodb-port
    - name: app-lb
      protocol: TCP
      port: 80
      targetPort: app-port
