apiVersion: v1
kind: Pod
metadata:
  name: hack-day-pod
  labels:
    name: hack-day
spec:
  containers:
    - name: mongodb
      image: docker.io/mongo:latest
      ports:
        - name: mongodb-port
          containerPort: 27017
      volumeMounts:
        - mountPath: /data/db
          name: db-volume
    - name: app
      image: docker.io/mehtaphysical/hack-day-app:v1
      env:
        - name: MONGODB_URI
          value: mongodb://localhost:27017
      ports:
        - name: app-port
          containerPort: 7890
  initContainers:
    - name: mongodb-data-permissions
      image: docker.io/busybox
      command: ["/bin/chmod", "-R", "777", "/data"]
      volumeMounts:
        - mountPath: /data
          name: db-volume
  volumes:
    - name: db-volume
      persistentVolumeClaim:
        claimName: hack-day-pvc
